### PR TITLE
Change import Veriff as named import

### PR DESCRIPTION
**Pull request by EhsanParsania**
I tried to import Veriff as default in ES6 style but it didn't work , It seems it is not exported as default , but in document it is imported as default , so I changed as named export and it worked well.

### CODE REVIEW

**Review by fixmk — APPROVED** [review]
Looks good to me :) Thank you for noticing this issue.

**Review by fixmk — CHANGES_REQUESTED** [review]
Actually small thing over there - styling. Could you please bring spaces around "Veriff" ?
(Ref: https://eslint.org/docs/rules/object-curly-spacing)

**Comment by EhsanParsania** [comment]
I applied the requested change in style.

**Review by fixmk — APPROVED** [review]
Thank you ! Today I will merge it along with package bump (https://github.com/Veriff/veriff-js-sdk/pull/28) :)

**Pull request merged**
